### ISSUE TITLE
Cannot upgrade to RestAssured 4.3.0

### ISSUE THREAD

**Issue by rdruss** [openshift-vertx-examples/vertx-cache-example-redhat#130]
Upgrading from 4.2.0 to 4.3.0 results in this error:

```
testHealth(io.openshift.example.CuteNameServiceVerticleTest)  Time elapsed: 0.896 sec  <<< ERROR!
java.lang.AbstractMethodError: Receiver class io.restassured.internal.ResponseParserRegistrar does not define or inherit an implementation of the resolved method 'abstract java.lang.Object getProperty(java.lang.String)' of interface groovy.lang.GroovyObject.
        at org.codehaus.groovy.runtime.callsite.PogoGetPropertySite.getProperty(PogoGetPropertySite.java:50)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGroovyObjectGetProperty(AbstractCallSite.java:307)
        at io.restassured.internal.ResponseParserRegistrar.<init>(ResponseParserRegistrar.groovy:44)
        at io.restassured.RestAssured.createTestSpecification(RestAssured.java:1448)
        at io.restassured.RestAssured.given(RestAssured.java:653)
        at io.restassured.RestAssured.get(RestAssured.java:720)
        at io.openshift.example.CuteNameServiceVerticleTest.lambda$setUp$0(CuteNameServiceVerticleTest.java:37)
        at org.awaitility.core.CallableCondition$ConditionEvaluationWrapper.eval(CallableCondition.java:100)
        at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:190)
        at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:177)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:830)

testWeGetName(io.openshift.example.CuteNameServiceVerticleTest)  Time elapsed: 0.213 sec  <<< ERROR!
java.lang.AbstractMethodError: Receiver class io.restassured.internal.ResponseParserRegistrar does not define or inherit an implementation of the resolved method 'abstract java.lang.Object getProperty(java.lang.String)' of interface groovy.lang.GroovyObject.
        at org.codehaus.groovy.runtime.callsite.PogoGetPropertySite.getProperty(PogoGetPropertySite.java:50)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGroovyObjectGetProperty(AbstractCallSite.java:307)
        at io.restassured.internal.ResponseParserRegistrar.<init>(ResponseParserRegistrar.groovy:44)
        at io.restassured.RestAssured.createTestSpecification(RestAssured.java:1448)
        at io.restassured.RestAssured.given(RestAssured.java:653)
        at io.restassured.RestAssured.get(RestAssured.java:720)
        at io.openshift.example.CuteNameServiceVerticleTest.lambda$setUp$0(CuteNameServiceVerticleTest.java:37)
        at org.awaitility.core.CallableCondition$ConditionEvaluationWrapper.eval(CallableCondition.java:100)
        at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:190)
        at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:177)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:830)


Results :

Tests in error: 
  testHealth(io.openshift.example.CuteNameServiceVerticleTest): Receiver class io.restassured.internal.ResponseParserRegistrar does not define or inherit an implementation of the resolved method 'abstract java.lang.Object getProperty(java.lang.String)' of interface groovy.lang.GroovyObject.
  testWeGetName(io.openshift.example.CuteNameServiceVerticleTest): Receiver class io.restassured.internal.ResponseParserRegistrar does not define or inherit an implementation of the resolved method 'abstract java.lang.Object getProperty(java.lang.String)' of interface groovy.lang.GroovyObject.

**Comment by rdruss** [comment]
Removed com.jayway.restassured dependency from pom and upgrade issue went away.  All tests still pass.  There a conflict in Groovy versions with the upgrade to io.restassured 4.3.0. io.restassured brought in groovy 3.0.2 while com.jayway.restassured was bringing in groovy 2.4.4.
